---
version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "npm"
    # Use the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
